site_name: Thimm
site_url: https://thimm.github.io
theme:
  name: "material"
  logo: assets/FarmOnLogoWhite.svg
  favicon: assets/FarmOnFavicon.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - search.highlight
    - search.suggest
    - navigation.instant

# Extensions
markdown_extensions:
  # - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list

  - toc:
      permalink: true

plugins:
  - search:
      lang: "en"
      #     prebuild_index: true
      indexing: "titles"
  - blog:
    blog_dir: blog
    blog_toc: true
  - rss:
      match_path: blog/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
